### ISSUE TITLE
tests code coverage

### ISSUE THREAD

**Issue by greut** [exoscale/terraform-provider-exoscale#147]
the goal is to reach at least 50% per resource, #135 - #145 

- [ ] `provider` 28% - need the `cloudstack.ini` parsing part
- [x] `affinity`88%
- [x] `compute` 55% - :sunglasses: #166 
- [ ] `domain` 48% - need `import`
- [x] `domain_record` 50% - :sunglasses: #161 
- [x] `ipaddress` 62%
- [x] `network` 56% - :sunglasses:  #153 
- [x] `nic` 78% - :sunglasses: #154
- [x] `secondary_ipaddress` 62% - :sunglasses: #156
- [x] `security_group` 53% - :sunglasses: #162
- [x] `security_group_rule` 80% - :sunglasses: #159
- [x] `ssh_keypair` 80%
- [x] `tags` 90% - :sunglasses: #165 
- [x] `validation` 100% - :sunglasses: #162 
----
- [x] global 60.7% :sun_with_face: #172

**Comment by greut** [comment]
More code coverage is always welcome though.
